column_renaming = {
    "id": "ID Parking",
    "nom": "Nom",
    "insee": "Code INSEE",
    "adresse": "Adresse",
    "url": "URL",
    "type_usagers": "Type Usagers",
    "gratuit": "Gratuit",
    "nb_places": "Nombre de Places",
    "nb_pmr": "Places PMR",
    "nb_voitures_electriques": "Places Voitures Électriques",
    "hauteur_max": "Hauteur Max (cm)",
    "tarif_1h": "Tarif 1h (€)",
    "tarif_2h": "Tarif 2h (€)",
    "tarif_3h": "Tarif 3h (€)",
    "tarif_4h": "Tarif 4h (€)",
    "tarif_24h": "Tarif 24h (€)",
    "type_ouvrage": "Type Ouvrage",
    "adresse_normalized": "Adresse Normalisée",
    "typo_match": "Correspondance Typo",
    "typo_normalized": "Typo Normalisée",
}